let date = new Date();
console.log(date);
console.log(date.toLocaleString());
console.log(date.toString());
console.log(date.toDateString());
console.log(date.toTimeString());
console.log(date.toUTCString());
console.log(date.toLocaleDateString());
console.log(date.toLocaleTimeString());
date = new Date();
console.log(date);
console.log(date.getDate());
console.log(date.getDay());
console.log(date.getFullYear());
console.log(date.getHours());
console.log(date.getTime());
console.log(date.setDate(5));
console.log(date.getDate());
console.log(date.setHours(5));
export {};
